#!/usr/bin/python3
# -*- coding: utf-8 -*-

import urllib.request, json

city = "Austin"
api_key = "4902bb01e7769cee7017b14a639f7a45" 

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 273.15)

print("%s, %i °C" % (info, temp))

